### ISSUE TITLE
FastLED 3.6.0 blink sketch does not compile for an ESP32-C6 on Arduino IDE 2.3.2

### ISSUE THREAD

**Issue by JanvidW** [FastLED/FastLED#1623]
I get the following error when trying to upload to an esp32 c6 dev board. I think this might be because the c6 is not currently supported? 

.../FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:349:6: error: #error Not yet implemented for unknown ESP32 target
  349 |     #error Not yet implemented for unknown ESP32 target
      |      ^~~~~
.../FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:415:6: error: #error Not yet implemented for unknown ESP32 target
  415 |     #error Not yet implemented for unknown ESP32 target
      |      ^~~~~
.../FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:461:10: error: #error Not yet implemented for unknown ESP32 target
  461 |         #error Not yet implemented for unknown ESP32 target
      |          ^~~~~

The part above can be fixed by including a case for the c6 in **clockless_rmt_esp32.cpp** but the errors below remain

In file included from .../Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32c6/include/esp_system/include/esp_system.h:14,
                 from .../Arduino15/packages/esp32/hardware/esp32/3.0.0-rc3/cores/esp32/esp32-hal.h:32,
                 from .../Arduino/libraries/FastLED/src/platforms/esp/32/led_sysdefs_esp32.h:2,
                 from .../Arduino/libraries/FastLED/src/led_sysdefs.h:42,
                 from.../Arduino/libraries/FastLED/src/FastLED.h:55,
                 from .../Arduino/libraries/FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:7:
.../FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::interruptHandler(void*)':
.../FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:466:31: error: 'tx_next_bit' was not declared in this scope
  466 |             if (intr_st & BIT(tx_next_bit)) {
      |                               ^~~~~~~~~~~
.../Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32c6/include/esp_common/include/esp_bit_defs.h:79:42: note: in definition of macro 'BIT'
   79 | #define BIT(nr)                 (1UL << (nr))
      |                                          ^~
.../Arduino/libraries/FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:472:35: error: 'tx_done_bit' was not declared in this scope
  472 |                 if (intr_st & BIT(tx_done_bit)) {
      |                                   ^~~~~~~~~~~
.../Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32c6/include/esp_common/include/esp_bit_defs.h:79:42: note: in definition of macro 'BIT'
   79 | #define BIT(nr)                 (1UL << (nr))
      |                                          ^~

exit status 1

Compilation error: exit status 1

**Comment by samguyer** [comment]
@JanvidW Would you mind trying out a fix for this problem and letting me know how it goes? I can walk you through it.

**Comment by netmindz** [comment]
Looks like S3 is the closest match, just with slightly different names, e.g `tx_stop_chn` vs `tx_stop_n`

**Comment by josephreisinger** [comment]
@netmindz I took your branch for a spin using ESP32C6 Dev Module and arduino-esp32 version 3.0.2. Compiles fine(!) but hit an abort loop when I upload the blink sketch. Serial monitor reports: 

```
E (132) rmt(legacy): CONFLICT! driver_ng is not allowed to be used with the legacy driver

abort() was called at PC 0x42006d43 on core 0
```

This is an otherwise clean Arduino IDE. Could be related to the specific device I'm trying (M5Stack Nano C6), but I don't have a more generic dev board handy. 

ESP32 internals at this level are pretty over my head but happy to lend a hand if anything would be helpful!

**Comment by netmindz** [comment]
It's very much a quick and dirty hack with no idea what I'm doing. I've commented on the values that are "magic values" for the other platforms for which I don't know where to find the appropriate ones for this platform. There might be other bits needed too.
Thought I might as well share what progress I'd made in case it helped catalyse someone else completing the work

**Comment by josephreisinger** [comment]
Makes sense! Looks like the same RMT legacy driver issue is popping up over here: https://github.com/FastLED/FastLED/issues/1631#issuecomment-2194817480 so might get fixed on that side.

**Comment by zackees** [comment]
Fix is merged:

https://github.com/FastLED/FastLED/pull/1652#event-13757340237

Waiting on a new release for arduino clients

**Comment by egnor** [comment]
(yeah, RMT issues with arduino-esp32 v3.x / ESP-IDF v5.x seem to be tracked in https://github.com/FastLED/FastLED/issues/1628 and https://github.com/FastLED/FastLED/issues/1631, with fixes in git? that's largely independent of -C6 support I think)

**Comment by per1234** [comment]
> does not compile for an ESP32-C6 on Arduino IDE 2.3.2

FYI, the IDE version is not the relevant factor. It is the "esp32" boards platform version that is the relevant factor. The Arduino IDE Boards Manager allows any version of any platform to be installed in any version of Arduino IDE, so the platform version is completely independent from the IDE version.

Arduino IDE only lists the boards that are provided by the installed platforms and executes the compilation and upload commands that are defined by the platform of the selected board. It doesn't know anything about the specifics of what is implemented in the platform.

**Comment by zackees** [comment]
Compiler errors have been fixed with the FastLED 3.7.1 bug fix release.

**Comment by michaelochs** [comment]
I am still seeing this issue when using the 3.7.1 release or current main branch:

```
.pio/libdeps/esp32c6/FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:372:6: error: #error Not yet implemented for unknown ESP32 target
  372 |     #error Not yet implemented for unknown ESP32 target
      |      ^~~~~
.pio/libdeps/esp32c6/FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:448:6: error: #error Not yet implemented for unknown ESP32 target
  448 |     #error Not yet implemented for unknown ESP32 target
      |      ^~~~~
.pio/libdeps/esp32c6/FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:494:10: error: #error Not yet implemented for unknown ESP32 target
  494 |         #error Not yet implemented for unknown ESP32 target
      |          ^~~~~
```

This happens with the esp32-c6-devkitm-1 board.

**Comment by netmindz** [comment]
The changes so far only allow for newer IDF version, my branch has the flags for C6 but not sure the right values to pass so doesn't currently produce working output

**Comment by zackees** [comment]
@netmindz can I ask that you fork this repo and put your code in here?

https://github.com/FastLED/PlatformIO-Starter

We don't have a ini file for the c6 flavor, but we do have one for the s3 which is pretty close:

https://github.com/FastLED/PlatformIO-Starter/tree/main/platforms

Would it be too much to ask to help us by creating an ini file for the c6? No is okay. But it will help us tremendously.

**Comment by netmindz** [comment]
I was testing with https://github.com/netmindz/C6Test

@zackees

**Comment by zackees** [comment]
Thanks for this.

I believe I tried your same packages for espressif and I don't remember that it worked well. I had to use this instead:

platform = https://github.com/zackees/platform-espressif32#Arduino/IDF5

I've used your code to create a new platformio.ini
https://github.com/FastLED/PlatformIO-Starter/blob/main/platforms/platformio.esp32c6.ini

**Comment by zackees** [comment]
Also your fork is old, can you please rebase it from master?

**Comment by netmindz** [comment]
> Also your fork is old, can you please rebase it from master?

Done. Just random guess based on copy and paste of existing code with the new naming.

I wouldn't assume anything there is correct

It's possible it's closer to the C3 and H2 than the S3 or could be totally different
